import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import react from 'eslint-plugin-react'
import prettier from 'eslint-config-prettier'
import globals from 'globals'

export default tseslint.config(
  {
    ignores: ['build/', 'dist/', 'dev-dist/', 'node_modules/', 'eslint.config.mjs'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  react.configs.flat.recommended,
  {
    files: ['src/**/*.{js,jsx,ts,tsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: { ...globals.browser },
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    settings: { react: { version: 'detect' } },
    rules: {
      // Possible Errors
      'for-direction': 'error',
      'getter-return': ['warn'],
      'no-await-in-loop': 'warn',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': ['warn', 'always'],
      'no-console': ['warn'],
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-dupe-args': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': ['error'],
      'no-empty-character-class': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-func-assign': 'error',
      'no-inner-declarations': ['error', 'both'],
      'no-invalid-regexp': ['error'],
      'no-irregular-whitespace': ['error'],
      'no-obj-calls': 'error',
      'no-regex-spaces': 'warn',
      'no-sparse-arrays': 'error',
      'no-template-curly-in-string': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'use-isnan': 'error',
      'valid-typeof': ['error'],
      // Best Practices
      'accessor-pairs': ['warn'],
      'array-callback-return': ['warn', { allowImplicit: true }],
      'block-scoped-var': 'warn',
      'class-methods-use-this': ['warn'],
      complexity: ['warn', { max: 20 }],
      'consistent-return': ['error'],
      curly: ['error'],
      'default-case': ['error'],
      'dot-notation': ['error'],
      eqeqeq: ['error', 'smart'],
      'guard-for-in': 'off',
      'no-alert': 'warn',
      'no-caller': 'error',
      'no-case-declarations': 'warn',
      'no-div-regex': 'error',
      'no-else-return': ['error', { allowElseIf: false }],
      'no-empty-function': ['warn'],
      'no-empty-pattern': 'error',
      'no-eval': ['error'],
      'no-extend-native': ['error'],
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-fallthrough': [
        'error',
        { commentPattern: 'break[\\s\\w]*omitted | no\\s?break' },
      ],
      'no-global-assign': ['error'],
      'no-implicit-coercion': ['off'],
      'no-implicit-globals': ['off'],
      'no-implied-eval': ['error'],
      'no-invalid-this': 'error',
      'no-iterator': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-loop-func': 'error',
      'no-multi-str': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-octal': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': ['warn'],
      'no-proto': 'error',
      'no-redeclare': ['error'],
      'no-restricted-properties': 'off',
      'no-return-assign': 'error',
      'no-script-url': 'error',
      'no-self-assign': ['error'],
      'no-self-compare': 'error',
      'no-sequences': ['warn'],
      'no-throw-literal': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unused-expressions': ['error'],
      'no-unused-labels': 'error',
      'no-useless-call': 'error',
      'no-useless-concat': 'error',
      'no-useless-escape': 'error',
      'no-useless-return': 'error',
      'no-void': 'error',
      'no-warning-comments': 'warn',
      'no-with': 'error',
      'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
      radix: 'error',
      'require-await': 'warn',
      'vars-on-top': 'warn',
      'wrap-iife': ['warn', 'inside'],
      yoda: ['error', 'never', { exceptRange: true }],
      'react/no-children-prop': 'warn',
      'prefer-const': 'warn',
      'no-prototype-builtins': 'off',
      'react/no-unescaped-entities': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },
  prettier
)
