name: Publish Docker image(prod)

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
    paths:
    - '.github/**'
    - 'docker/**'
    - 'public/**'
    - 'src/**'
    - 'package.json'
    - 'package-lock.json'
    - 'Dockerfile'
    - 'Dockerfile-dev'
    - 'nginx-default.conf'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: yoneyan/homenoc-dsbd-web-admin

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
