name: Publish Docker image(v5)

on:
  push:
    branches:
      - v5.x
    paths:
    - '.github/**'
    - 'docker/**'
    - 'public/**'
    - 'src/**'
    - 'package.json'
    - 'package-lock.json'
    - 'Dockerfile'
    - 'Dockerfile-dev'
    - 'nginx-default.conf'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: yoneyan/homenoc-dsbd-web-admin:v5
          labels: "dsbd-web v5"
